"""phase2_inventory_access_trainer

Revision ID: 4a66e532d066
Revises: 0001
Create Date: 2026-07-15 16:19:29.555239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4a66e532d066'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='inventory_items_quantity_non_negative'),
    sa.CheckConstraint('sale_price IS NULL OR sale_price > 0', name='inventory_items_sale_price_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_logs',
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('reader', sa.String(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("result IN ('authorized','expiring_soon','expired','blocked','temporary_access','invalid_token')", name='access_logs_result_valid'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_sales',
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('registered_by', sa.UUID(), nullable=True),
    sa.Column('cancelled_by', sa.UUID(), nullable=True),
    sa.Column('cancel_reason', sa.String(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainer_clients',
    sa.Column('trainer_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', name='trainer_clients_client_id_key')
    )
    op.create_table('inventory_sale_items',
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='inventory_sale_items_quantity_positive'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['inventory_sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Nota: el autogenerate también detectó 3 índices `ix_*_gym_id`
    # preexistentes en members/membership_plans/users como "de más" (drift
    # entre la migración 0001 y los modelos actuales — no declarados con
    # index=True en el modelo). Fuera de alcance de esta migración: no se
    # tocan, para no mezclar una limpieza no solicitada con las tablas
    # nuevas de este cambio.
    op.create_index('inventory_items_gym_id_idx', 'inventory_items', ['gym_id'])
    op.create_index('inventory_sales_gym_id_idx', 'inventory_sales', ['gym_id'])
    op.create_index('access_logs_gym_id_idx', 'access_logs', ['gym_id'])
    op.create_index('access_logs_member_id_idx', 'access_logs', ['member_id'])
    op.create_index('trainer_clients_trainer_id_idx', 'trainer_clients', ['trainer_id'])
    op.create_index('inventory_sale_items_sale_id_idx', 'inventory_sale_items', ['sale_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_sale_items')
    op.drop_table('trainer_clients')
    op.drop_table('inventory_sales')
    op.drop_table('access_logs')
    op.drop_table('inventory_items')
    # ### end Alembic commands ###
